name: build-and-deploy

on:
  push:
    branches: master


jobs:
  build:
    runs-on: windows-latest


    steps:
    - uses: actions/checkout@v2
    
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
           
 
    - name: Setup NuGets
      uses: NuGet/setup-nuget@v1.0.2
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          
  
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      

    - name: Create Build Directory
      run: mkdir build
   
  
    - name: Restore Packages
      run: nuget restore Emmetienne.ChipOtto.sln
      

    - name: Build Solution
      run: |
        msbuild.exe Emmetienne.ChipOtto.sln /p:platform="Any CPU" /p:configuration="Release" /p:AllowUnsafeBlocks=true
        
           
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ChipOtto
        path: "./build"
        
        
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.1
      with:
          filename: ChipOtto.zip
          path:  D:\a\Emmetienne.ChipOtto\Emmetienne.ChipOtto\bin\release\ 
          directory: D:\a\Emmetienne.ChipOtto\Emmetienne.ChipOtto\build\
          type: zip     
          
       
    - name: Set date as ENV variable
      run: echo "NOW=$(date +’%Y-%m-%d_%H-%M-%S’)" >> $env:GITHUB_ENV
      
      
    - name: Print current date
      run: echo ${env:NOW}
     
     
    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
         draft: false
         prerelease: false
         release_name: "ChipOtto_${{ env.NOW }}"
         tag_name: ${{ env.NOW }}
      env:
         GITHUB_TOKEN: ${{ github.token }}   
   
   
    - name: Upload release asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: d:/a/Emmetienne.ChipOtto/Emmetienne.ChipOtto/build/ChipOtto.zip
        asset_name: ChipOtto.zip
        asset_content_type: application/zip
    
